version: '3.4'

services:
  mediathekar:
    image: ${DOCKER_REGISTRY-}mediathekar
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=http://*:5000
    ports:
    - "5000:5000"
    build:
      context: .
      dockerfile: Mediathekar/Dockerfile
    volumes:
    - /c/test:/tv
    - /c/test:/movies
